-- AlterTable
ALTER TABLE "Folder" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "deleted_at" TIMESTAMP(3),
ADD COLUMN     "isDeleted" BOOLEAN,
ADD COLUMN     "updated_at" TIMESTAMP(3);
